### ISSUE TITLE
Configurable region when getting authorization token

### ISSUE THREAD

**Issue by gohmc** [aws-containers/amazon-ecr-public-creds-helper-script-for-k8s#1]
Can we make the [get authorization token call](https://github.com/aws-containers/amazon-ecr-public-creds-helper-script-for-k8s/blob/f4c6753ea74232df902bff9e368d2d0fdfe1f2ea/entrypoint.sh#L9) to local region instead of always going to us-east-1? We can add an [environment variable](https://github.com/aws-containers/amazon-ecr-public-creds-helper-script-for-k8s/blob/f4c6753ea74232df902bff9e368d2d0fdfe1f2ea/cronjob.yaml#L23) here and refer it in the script above. Happy to do a PR if needed.

**Comment by toricls** [comment]
Thank you @gohmc for raising this issue :)

The hard-coded region code you linked is an intended implementation because the `GetLoginPassword` API for Amazon ECR Public is only available in `us-west-1` today.

See more details in the [official docs](https://docs.aws.amazon.com/AmazonECR/latest/public/public-registries.html#get-login-password).

**Comment by gohmc** [comment]
Ok, thanks for the head-up. Hopefully one day there will be a regional endpoint for this.
